### ISSUE TITLE
DNS Issues With Latest Repo Additions

### ISSUE THREAD

**Issue by danvau7** [cisagov/dotgov-data#10]
Let me give one example. Why does the State of Wyoming have 9 different .gov TLDs? 

Why does this exist? I read the Amy Sebring piece from DHS in 2005 as well.  https://helicoptersofdc.com/

Just double checking some things. Thank you so much guys!

**Comment by h-m-f-t** [comment]
Hi @danvau7. What domains are you referring to? Wyoming has more than 9 .gov domains, which they are welcome to claim under our [requirements](https://home.dotgov.gov/registration/requirements/).

(I love the helicoptersofdc.com site!)

**Comment by h-m-f-t** [comment]
Closing for now. Feel free to reopen, @danvau7.
