### ISSUE TITLE
Clarification for anything USCG related whether .mil or .gov

### ISSUE THREAD

**Issue by danvau7** [cisagov/dotgov-data#11]
Hi All:

As you know the US Coast Guard, since Katrina, has always been tasked with Homeland Security missions. Part of it is under DHS, part of it is the Military. Can we get clarity who works with what part for an USCS contacts? This is especially important for foreign naval officers who are trying to determine how to legally follow US law. Thank you so much!

**Comment by h-m-f-t** [comment]
Hi @danvau7. The US Coast Guard is a component of Homeland Security, but operates under the Department of Defense for military operations. They have uscg.mil registered and _could_ register a .gov domain. However, we're not in a position to articulate how communication with USCG should happen.
