### ISSUE TITLE
Update gov.txt directly from zone

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/dotgov-data#118]
In #107, we updated gov.txt (a copy of the zone file) each day from the version we [publish each day to CZDS](https://get.gov/posts/2022-09-14-making-infrastructure-less-invisible/#publishing-the-.gov-zone-file). Instead of pulling once daily from a copy, we should pull from our DNS provider, Cloudflare.

## Acceptance criteria
- [x] Get read-only API token from Cameron
- [x] Decide if we want to strip the zone file's comment header (the order of this file is also slightly different than CZDS)  - as of July 8/2024, the zone file currently matches Cloudflare's zone file format rather than CZDS's
- [x] gov.txt is updated daily via this new source
  - [x] Merge every 24 hours 
- [x] [ADR](https://github.com/cisagov/dotgov-data/blob/main/docs/architecture/0001-automated-zone-file-updates.md) is updated with any necessary changes based on this work

### Additional Context
It's recommended that you fork the dotgov-data repo for this work.

We intend to eventually poll more frequently than 24 hours since the provenance of the data is the real source. In this issue, the goal is to simply replace where we're sourcing.

**Comment by PaulKuykendall** [comment]
@h-m-f-t - in Fireside, we reviewed this and wanted your feedback on the actual priority on this item. It's fairly high in the backlog now.

**Comment by h-m-f-t** [comment]
It's true this isn't super urgent. However, one of my reasons for it being high in the backlog is that it is similar to the work recently done to archive the CZDS zone file and so it may be easy to pick up.

**Comment by h-m-f-t** [comment]
I lightly updated the issue to de-scope questions about multiple commits in a PR. (When we poll more frequently, we'll want to see individual daily commits but summarize the daily diff into one (perhaps this is a PR, though we don't want to approve a PR before merging).
