### ISSUE TITLE
Non-US States in "State" Information

### ISSUE THREAD

**Issue by CNX-Inc** [cisagov/dotgov-data#142]
I was surprised to find a non-US State, and what I presume is a City, in the `State` field for one of the Domains.

| Domain name           | Domain type         | Agency              | Organization name     | City    | State | Security contact email       |
|-----------------------|---------------------|---------------------|-----------------------|---------|-------|------------------------------|
| usaseanconnect.gov    | Federal - Executive | Department of State | U.S. - ASEAN Connect  | Jakarta | Ja    | VDPSubmission@state.gov      |

**Comment by h-m-f-t** [comment]
For legacy (pre-Nov 2023) domains, `City` and `State` are asserted values that are associated with the domain request and don't have anything to do with a domain's operation. This is certainly an oddity – and it also doesn't matter 😄 – so I've updated it to Washington D.C. It should update on the next push.
