### ISSUE TITLE
atf.gov  Bureau of Alcohol, Tobacco, Firearms and Explosives is missing from the list.

### ISSUE THREAD

**Issue by psabela** [cisagov/dotgov-data#146]
atf.gov  Bureau of Alcohol, Tobacco, Firearms and Explosives is missing from the list.

**Comment by mcdonnnj** [comment]
Isn't it right here https://github.com/cisagov/dotgov-data/blob/main/current-federal.csv#L446?

**Comment by psabela** [comment]
I cannot find it when I go here:   https://github.com/cisagov/dotgov-data/blob/main/current-federal.csv
and many more domains like gsa.gov is missing.

**Comment by mcdonnnj** [comment]
The list is not alphabetical and `gsa.gov` is at https://github.com/cisagov/dotgov-data/blob/main/current-federal.csv#L943. You may want to try downloading the file and searching the `Domain name` column specifically to find what you need.
