### ISSUE TITLE
Mark Department of Defense component domains as DoD

### ISSUE THREAD

**Issue by konklone** [cisagov/dotgov-data#75]
`intelligencecareers.gov` and `lps.gov` are marked as NSA, rather than DoD. Is that intended? It seems like NSA should be the `Organization` field with DoD as the `Agency`.

**Comment by konklone** [comment]
Also, `cap.gov` and `capnho.gov` are marked as `Civil Air Patrol`, but that appears to be a component of the U.S. Air Force, which itself is a component of the Department of Defense.

**Comment by konklone** [comment]
Interestingly, Armed Forces Retirement Home looks to be an `independent establishment in the executive branch`, according to its [founding statute](https://www.afrh.gov/sites/default/files/2021_24USC_Chapter10_AFRH_0.pdf), but according to its [org chart](https://www.afrh.gov/sites/default/files/20220310_AFRH_OrganizationChart.pdf), its CEO is a DoD employee and the COO is appointed by the secretary of DoD. I'm not recommending this be changed, since the statute seems clear, but documenting it here for the record.

**Comment by h-m-f-t** [comment]
Changes pending for the CAP and NSA domains.

**Comment by h-m-f-t** [comment]
Fixed in e42c9eb5cec600e40df0846dbca35a4d284fcf60.
