### ISSUE TITLE
promesa.gov is marked as Federal and Non-Federal

### ISSUE THREAD

**Issue by konklone** [cisagov/dotgov-data#76]
The `promesa.gov` domain is marked as `Federal - Executive` but as a `Non-Federal Agency` in the `Agency` field. Is that inaccurate? Or is there a way to make it less confusing?

**Comment by konklone** [comment]
Oh now this is confusing:

From [the website](https://oversightboard.pr.gov/about-us/):

![image](https://user-images.githubusercontent.com/4592/201497297-f6c3c683-2ee7-4cbc-9e02-e0319a11cb35.png)

And [the founding act says](https://drive.google.com/file/d/13samB-s8eL7gbFwUVI46l8lrCl1WWj_e/view):

![image](https://user-images.githubusercontent.com/4592/201497314-9d52b056-a225-4aff-9ba8-d5bd09600ebb.png)

So, I think this should be marked as a State domain and not a `Federal - Executive` domain - what do you think?

**Comment by danvau7** [comment]
Why does the promesa.gov domain exist? I checked historical DNS, it does not appear a website has ever been attached to that domain.

**Comment by h-m-f-t** [comment]
Thanks @konklone! Change submitted.

@danvau7 – Domain names needn't be used for websites; they aren't equivalent terms.

**Comment by h-m-f-t** [comment]
Fixed at c70ec82d69f8affcd7d4c2223c2273030417c101.
