### ISSUE TITLE
nnss.gov is marked as NNSA, should be DoE

### ISSUE THREAD

**Issue by konklone** [cisagov/dotgov-data#77]
The National Nuclear Security Administration is a (large) component of the Department of Energy - should this be updated?

**Comment by h-m-f-t** [comment]
Yes, thanks! Edit proposed in our registrar, landing in the next day or so.

**Comment by h-m-f-t** [comment]
Fixed at e42c9eb5cec600e40df0846dbca35a4d284fcf60.
