### ISSUE TITLE
OIG entries should mark OIG as the Organization, not Agency 

### ISSUE THREAD

**Issue by konklone** [cisagov/dotgov-data#78]
The `Agency` field for `stateoig.gov` is listed as `Department of State, Office of Inspector General`, and it seems like this should match other agency OIG domains and use `Department of State` as the `Agency` and `Office of Inspector General` as the `Office`.

**Comment by konklone** [comment]
Same for `Corporation for National and Community Service, Office Of Inspector General`. Also, that field uses an `and` while the CNSC entries above it use an `&`, so opportunity for typographical consistency as well. ;)

**Comment by konklone** [comment]
Some others:

* `United States Postal Service, Office of Inspector General` (this appears twice, once for peacecorpsoig.gov, which looks like an error - will file separate issue)
* `United States International Trade Commission, Office of Inspector General`
* `Federal Housing Finance Agency, Office of Inspector General`

I realize that adds up to 5 examples - but there are at least as many counter-examples. So, it seems worth making it consistent, and I would recommend moving the OIG name to be designated in the `Office` since they are (though independent) a component of the parent agency.

**Comment by h-m-f-t** [comment]
Solid, thanks! Changes pending in the registry.

**Comment by h-m-f-t** [comment]
With the exception of USPS OIG, all fixed in e42c9eb5cec600e40df0846dbca35a4d284fcf60. Leaving this open until USPS OIG is correctly agency'd.

**Comment by h-m-f-t** [comment]
USPS OIG's agency label was corrected at c5b96d1ea447057ed1373bca5e383ea30b1d2421. Closing this issue; thanks again @konklone.
