### ISSUE TITLE
peacecorpsoig.gov has an incorrect agency field

### ISSUE THREAD

**Issue by konklone** [cisagov/dotgov-data#79]
peacecorpsoig.gov has the wrong `Agency` field:

![image](https://user-images.githubusercontent.com/4592/201497772-83652881-132d-46ad-af64-2feb6dff15da.png)

I had originally filed this in #62 in June but apparently I mistyped the issue name and added an extra `.`, leading to confusion.

I recommend in #78 that this be corrected to use the parent agency as the `Agency` field and the OIG component name as the `Organization`.

**Comment by h-m-f-t** [comment]
Clearly! Thanks for the flag; change is pending, in alignment with #78.

**Comment by h-m-f-t** [comment]
Fixed in e42c9eb5cec600e40df0846dbca35a4d284fcf60
