### ISSUE TITLE
StatDNS uses this dataset for statistical purposes

### ISSUE THREAD

**Issue by fcambus** [cisagov/dotgov-data#96]
[StatDNS](https://www.statdns.com) is a DNS research project publishing monthly TLD zone files statistics highlighting the deployment of DNSSEC and IPv6 within the top-level domains.

Since .gov data has been made public, I have been processing the zone file dump to include the results in our monthly reports.

However, I noticed that despite the CSV files being updated on a regular basis, the gov.txt file hasn't been updated in 6+ months now. Is there any plan to update it on a more regular basis, or to publish it on ICANN's CZDS service?

**Comment by h-m-f-t** [comment]
Hi @fcambus. .gov [is available in CZDS](https://get.gov/updates/2022/9/14/making-infrastructure-less-invisible/#publishing-the-gov-zone-file). We anticipate co-publishing the zone regularly to this repo, too, but haven't been able to prioritize that task recently.

Closing this issue now, but feel free to re-open if you have any other questions.
